# Generated by Django 3.2.6 on 2024-06-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='email',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='land_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
